### ISSUE TITLE
Keep track of unsent mails.

### ISSUE THREAD

**Issue by visheshruparelia** [zense/alumni-dashboard#13]

**Comment by visheshruparelia** [comment]
@arkokoley Help required here, can't think of a solution.

**Comment by arkokoley** [comment]
Use something akin to sidekiq_mailer  @ https://github.com/andersondias/sidekiq_mailer to send mails asynchronously so that the sender doesn't have to wait till all the mails are sent. 

So what sidekiq_mailer does is, makes a queue of all the emails to be send and sends them as and when it can. This offloads the trigger from the main process which can terminate as and when it can. 

I suppose, it is possible to get a list of mails which were sent and which were not from sidekiq_mailer.

**Comment by arkokoley** [comment]
@vibhavagarwal5 I had asked you to follow up with a method using ActiveJobs. Any progress on that?

**Comment by vibhavagarwal5** [comment]
None.
I have to start it.

**Comment by visheshruparelia** [comment]
I've used the deliver_later method of ActionMailer and setup the queuing server to sidekiq so as to send asynchronously. I hope this is a correct way to do it @arkokoley

**Comment by arkokoley** [comment]
@visheshruparelia That is the correct way of doing this.
